using UnityEngine;

namespace EasyIdleGame
{
    /// <summary>
    /// Generic source category propagated through item additions, events, and contextual effects.
    /// </summary>
    public enum SourceType
    {
        [Tooltip("Matches every source.")]
        Any = 0,

        [Tooltip("Changes without a more specific source category.")]
        Generic = 1,

        [Tooltip("Changes originating from a recurring or scheduled grant.")]
        RecurringReward = 2,

        [Tooltip("Changes originating from a purchase or transaction.")]
        Purchase = 3,

        [Tooltip("Changes originating from an advertisement interaction.")]
        Advertisement = 4,

        [Tooltip("Changes originating from reaching a milestone.")]
        Milestone = 5,

        [Tooltip("Changes originating from a reset or restart flow.")]
        Reset = 6,

        [Tooltip("Changes originating from converting one or more items into others.")]
        Conversion = 7,

        [Tooltip("Limited-time event changes.")]
        Event = 8,

        [Tooltip("Changes originating from a random drop or loot roll.")]
        RandomDrop = 9,

        [Tooltip("Changes generated by normal business production.")]
        Production = 10
    }
}
